### ISSUE TITLE
Listing format displays backslash not forward slash

### ISSUE THREAD

**Issue by cromemcos** [dwildie/cromix-fs#1]
I know this is a bit picky but in this Unix well Cromix world I wanted to see a forward slash when there is a listing.  Here is an example ...

C:\tmp>java -jar cromix-fs-1.1-jar-with-dependencies.jar -l XXU_Software_Test_Software_from_CG_10-29-86_OK_9-93.imd
Reading IMD file XXU_Software_Test_Software_from_CG_10-29-86_OK_9-93.imd
IMD 1.17: 02/00/2021 10:57:12
File generated by the HxC Floppy Emulator software v2.13.1.2

Read 154 tracks
Disk format: CLDSDD

       24 D  1 rewa re-- re-- 32767 32767 \bin
     1432 F  1 rewa ---- ---- 32767 32767 \bin\boot.bin
     3824 F  1 rewa -e-- -e--     0     0 \bin\copy.bin
     7134 F  1 rewa -e-- -e--     0     0 \bin\cptree.bin
     5450 F  1 rewa -e-- -e-- 32767 32767 \bin\dcheck.bin
      827 F  1 rewa -e-- -e-- 32767 32767 \bin\echo.bin
     1172 F  1 rewa -e-- -e-- 32767 32767 \bin\flush.bin
    15544 F  1 rewa -e-- -e--     0     0 \bin\ftar.bin
     6895 F  1 rewa -e-- -e-- 32767 32767 \bin\icheck.bin
     8587 F  1 rewa -e-- -e-- 32767 32767 \bin\ls.bin
     1576 F  1 rewa ---- ---- 32767 32767 \bin\makdev.bin
     1660 F  1 rewa -e-- -e-- 32767 32767 \bin\maklink.bin
    14020 F  1 rewa -e-- -e-- 32767 32767 \bin\mode.bin
     7343 F  1 rewa -e-- -e--     0     0 \bin\mount.bin
     4397 F  1 rewa -e-- -e--     0     0 \bin\move.bin
     5002 F  1 rewa -e-- -e--     0     0 \bin\unmount.bin
     3462 F  1 rewa ---- ---- 32767 32767 \bin\wboot.bin
    17947 F  1 rewa re-- re--     0     0 \bin\debug68.bin
     4852 F  1 rewa ---- ---- 32767 32767 \bin\makfs.bin
     9492 F  1 rewa ---- ---- 32767 32767 \bin\initflop.bin
      917 F  1 rewa -e-- -e-- 32767 32767 \bin\free.bin
    37660 F  1 rewa -e-- -e-- 32767 32767 \bin\asm68.bin
    25600 F  1 rewa -e-- -e-- 32767 32767 \bin\link68.bin
       78 F  1 rewa -e-- -e-- 32767 32767 \bin\restrp.bin
    28224 F  1 rewa -e-- -e-- 32767 32767 \bin\ddt.bin
        5 D  1 rewa re-- re-- 32767 32767 \cmd

**Comment by dwildie** [comment]
Java has used the separator character for the system, in this case Windows, it is being executed on.  When executed on a Linux system it does use the forward slash as the separator character.
Since we are dealing with a Cromix filesystem, it does make sense to always use a forward slash.

**Comment by dwildie** [comment]
Corrected in release 1.2
