### ISSUE TITLE
Extraction Dates

### ISSUE THREAD

**Issue by cromemcos** [dwildie/cromix-fs#2]
I notice that when files are extracted with the -x option the creation and modification dates are set to right now.   In other words the real dates imbedded inside the .IMD are therefore lost.    Could there be an option to write out the extraction with original dates?

![dates](https://user-images.githubusercontent.com/66743628/116823173-ed44c900-ab7a-11eb-8fe5-0030e90d24be.jpg)

**Comment by dwildie** [comment]
Yes, however, the filesystem timestamps are stored as 6 byte values which I haven't looked at decoding yet.

**Comment by dwildie** [comment]
Corrected in release 1.2
